import "@fontsource/inter/400.css";
import "@fontsource/inter/800.css";
import "@fontsource/ibm-plex-sans/400.css";
import "@fontsource/ibm-plex-sans/700.css";
import "@fontsource/ibm-plex-sans/400-italic.css";
import "@fontsource/ibm-plex-sans/700-italic.css";
import "@fontsource/ibm-plex-mono/";
import "./src/styles/prism.css";
import "./src/styles/markdown.css";
